# Generated by Django 4.2.2 on 2023-06-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TblZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.tblcolegio')),
            ],
        ),
    ]
